modLoader="javafml"
loaderVersion="[46,)"
license="MIT License"
[[mods]] #mandatory
modId="mysterious_mountain_lib" 
version="${file.jarVersion}"
displayName="Mysterious Mountain Lib" 
credits="MCMOD.cn"
authors="Syameimaru Zheng"
description='''
This is the library for Syameimaru Zheng's most of mods.
The most convenient library you will ever use.
'''
[[dependencies.mysterious_mountain_lib]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mysterious_mountain_lib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
