modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
[[mods]] #mandatory
modId="mmlib" 
version="${file.jarVersion}"
displayName="Mysterious Mountain Lib" 
credits="MCMOD.cn"
authors="Syameimaru Zheng"
description='''
This is the library for Syameimaru Zheng's most of mods.
The most convenient library you will ever use.
'''
[[dependencies.mmlib]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mmlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
